version: "3.0"

services:
  nodejs:
    build: '.'
    volumes:
      - .:/andre/dh/avanade/src/app
      - /andre/dh/avanade/src/app/node_modules
    depends_on: 
      - db
    ports:
      - "8080:3000"
    networks: 
      - app-connect
  
  db:
    image: postgres:13
    restart: unless-stopped
    ports: 
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks: 
      - app-connect

volumes:
  postgres-data:

networks:
  app-connect:
    driver: bridge