GET http://localhost:3000
###

GET http://localhost:3000/saudacao?nome=Geraldo&idade=18&cpf=123456789

###

GET http://localhost:3000/alunos
###

POST http://localhost:3000/alunos
Content-Type: application/json

{
    "nome": "Leonardo",
    "email": "leonardo@gmail.com",
    "matricula": "123"
}

###

DELETE http://localhost:3000/alunos/1

###

PUT http://localhost:3000/alunos/123edas2
Content-Type: application/json

{
        "nome": "Andre"
}

###
PATCH  http://localhost:3000/alunos/12/email
Content-Type: application/json

{
    "email": "geraldo@digitalhouse.com"
}

###
GET http://localhost:3000/cursos
###

POST http://localhost:3000/cursos
Content-Type: application/json

{
    "nome": "Fullstack JAVA",
    "codigo": "12"
}

###
DELETE http://localhost:3000/cursos/12

### 
PUT http://localhost:3000/cursos/1
Content-Type: application/json

{
    "codigo": "0921"
}
