GET http://localhost:3000
###

GET http://localhost:3000/saudacao?nome=Geraldo&idade=18&cpf=123456789

###

GET http://localhost:3000/alunos
###

POST http://localhost:3000/alunos
Content-Type: application/json

{
    "nome": "Andre",
    "matricula": "123edas2",
    "email": "apatricio@digitalhouse.com"
}

###

DELETE http://localhost:3000/alunos/123

###

PUT http://localhost:3000/alunos/131
Content-Type: application/json

{
        "nome": "Andre",
        "idade": 30,
        "matricula": 131
}

###
GET http://localhost:3000/cursos
###

POST http://localhost:3000/cursos
Content-Type: application/json

{
    "nome": "Android",
    "codigo": "1234"
}